// export const gasBaseUrl = 'https://api.debank.com/chain/gas_price_dict_v2?chain=';
export const gasBaseUrl = 'https://openapi.debank.com/v1/wallet/gas_market?chain_id=';
export const usdBaseUrl = 'https://api.coingecko.com/api/v3/simple/price?vs_currencies=usd&ids=';

export const speedMarks = {
  slow: '🐢', normal: '🚘', fast: '🚀',
}

// Object for all possible chains with cooldowns in seconds
export const chains = {
  eth: {
    id: 'eth',
    name: 'Ethereum',
    gasSymbol: 'eth',
    gasCooldown: 15,
    usdSymbol: 'ethereum',
    usdCooldown: 15,
    nativeToken: 'ETH',
  },
  bsc: {
    id: 'bsc',
    name: 'Binance',
    gasSymbol: 'bsc',
    gasCooldown: 15,
    usdSymbol: 'binancecoin',
    usdCooldown: 15,
    nativeToken: 'BNB',
  },
  xdai: {
    id: 'xdai',
    name: 'Gnosis',
    gasSymbol: 'xdai',
    gasCooldown: 15,
    usdSymbol: 'xdai',
    usdCooldown: 15,
    nativeToken: 'XDAI',
  },
  matic: {
    id: 'matic',
    name: 'Polygon',
    gasSymbol: 'matic',
    gasCooldown: 15,
    usdSymbol: 'matic-network',
    usdCooldown: 15,
    nativeToken: 'MATIC',
  },
  ftm: {
    id: 'ftm',
    name: 'Fantom',
    gasSymbol: 'ftm',
    gasCooldown: 15,
    usdSymbol: 'fantom',
    usdCooldown: 15,
    nativeToken: 'FTM'
  },
  okt: {
    id: 'okt',
    name: 'OKC',
    gasSymbol: 'okt',
    gasCooldown: 15,
    usdSymbol: 'oec-token',
    usdCooldown: 15,
    nativeToken: 'OKT',
  },
  avax: {
    id: 'avax',
    name: 'Avalanche',
    gasSymbol: 'avax',
    gasCooldown: 15,
    usdSymbol: 'avalanche-2',
    usdCooldown: 15,
    nativeToken: 'ANT',
  },
  op: {
    id: 'op',
    name: 'Optimism',
    gasSymbol: 'op',
    gasCooldown: 15,
    usdSymbol: 'optimism',
    usdCooldown: 15,
    nativeToken: 'OP',
  },
  arb: {
    id: 'arb',
    name: 'Arbitrum',
    gasSymbol: 'arb',
    gasCooldown: 15,
    usdSymbol: 'ethereum',
    usdCooldown: 15,
    nativeToken: 'ETH',
  },
  celo: {
    id: 'celo',
    name: 'Celo',
    gasSymbol: 'celo',
    gasCooldown: 15,
    usdSymbol: 'celo',
    usdCooldown: 15,
    nativeToken: 'CELO',
  },
  movr: {
    id: 'movr',
    name: 'Moonriver',
    gasSymbol: 'movr',
    gasCooldown: 15,
    usdSymbol: 'moonriver',
    usdCooldown: 15,
    nativeToken: 'MOVR',
  },
  cro: {
    id: 'cro',
    name: 'Cronos',
    gasSymbol: 'cro',
    gasCooldown: 15,
    usdSymbol: 'crypto-com-chain',
    usdCooldown: 15,
    nativeToken: 'CRO',
  },
  boba: {
    id: 'boba',
    name: 'Boba',
    gasSymbol: 'boba',
    gasCooldown: 15,
    usdSymbol: 'boba-network',
    usdCooldown: 15,
    nativeToken: 'BOBA',
  },
};